language: php

php:
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - composer cscheck
  - composer phpstan
#  - composer behat
  - composer infection

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

# todo: update codecov config for phpunit report
