language: php

php:
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/behat

after_success:
  - bash <(curl -s https://codecov.io/bash)
